openapi: "3.0.0"
info:
  version: 1.0.0
  title: Rabeh Trader API documentation

servers:
  - url: https://rabe7entertainment.com/api/v1
  - url: http://rabeh.local/api/v1

security:
  - bearerAuth: []
paths:
  /trader/exchange-cash:
    post:
      summary: Exchange user cash with points
      operationId: exchangeCash
      tags:
        - Cash Exchange
      responses:
        201:
          description: created cash response
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Created'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    Voucher:
      type: object
      properties:
        id:
          type: number
        price:
          type: string
        expires_at:
          type: string
        name:
          type: string
        description:
          type: string
    Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
        message:
          type: string

    Created:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
        message:
          type: string
