openapi: "3.0.0"
info:
  version: 1.0.0
  title: Rabeh Users API documentation

servers:
  - url: https://rabe7entertainment.com/api/v1
  - url: http://rabeh.local/api/v1

security:
  - bearerAuth: []
paths:
  /auth/forgot-password:
    post:
      summary: Send reset password mail
      operationId: forgotPassword
      tags:
        - Forgot Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  description: user email
      responses:
        200:
          description: Email sent successfully respone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /referral-code:
    post:
      summary: Enter referral code
      operationId: referralCode
      tags:
        - Referral Code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                referral_code:
                  type: string
                  description: referral code
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Created'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /vouchers:
    get:
      summary: List all user vouchers
      operationId: listVouchers
      tags:
        - Vouchers
      responses:
        200:
          description: An array of vouchers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Voucher'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /voucher/redeem:
    post:
      summary: Redeem Voucher
      operationId: redeemVoucher
      tags:
        - Vouchers
      requestBody:
        required: true
        description: Points amount to be redeemed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedeemVoucherRequest'
      responses:
        200:
          description: Created Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Created'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /points/redeem:
    post:
      summary: Redeem points
      operationId: redeemPoints
      tags:
        - Points
      requestBody:
        required: true
        description: Points amount to be redeemed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedeemPointsRequest'
      responses:
        201:
          description: Redeemed points response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Created'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


  /tickets/redeem:
    post:
      summary: Redeem ticket
      operationId: redeemTicket
      tags:
        - Tickets
      requestBody:
        required: true
        description: Ticket ID to be redeemed
        content:
          application/json:
            schema:
              properties:
                ticket_id:
                  type: number
                  description: ticket id to be redeemed
      responses:
        201:
          description: Redeemed ticket response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Created'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Voucher:
      type: object
      properties:
        id:
          type: number
        price:
          type: string
        expires_at:
          type: string
        name:
          type: string
        description:
          type: string

    Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
        message:
          type: string

    Created:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
        message:
          type: string

    Message:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
        message:
          type: string

    RedeemPointsRequest:
      type: object
      required:
        - amount
      properties:
        points_amount:
          type: number
          description: Points amount

    RedeemVoucherRequest:
      type: object
      required:
        - voucher_id
      properties:
        voucher_id:
          type: number
          description: Voucher amount

    ReferralCodeRequest:
      type: object
      required:
        - referral_code
      properties:
        referral_code:
          type: string
          description: referral code
